name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Package (win-x64)
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Get version from project file
        id: version
        shell: pwsh
        run: |
          $csproj = Get-Content "SmoothRoller.csproj" -Raw
          if ($csproj -match '<AssemblyInformationalVersion>(.*?)</AssemblyInformationalVersion>') {
            $version = $matches[1]
          } elseif ($csproj -match '<AssemblyVersion>(.*?)</AssemblyVersion>') {
            $version = $matches[1] -replace '\.0$', ''
          } else {
            $version = "1.0.0"
          }
          Write-Output "version=$version" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
          Write-Output "Project version: $version"

      - name: Restore
        run: dotnet restore

      - name: Publish (framework-dependent single file, win-x64)
        run: dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true

      - name: Archive artifacts (zip)
        id: zip
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $dist = "dist\\win-x64"
          if (-not (Test-Path $dist)) {
            $dist = "bin\\Release\\net6.0-windows\\win-x64\\publish"
          }
          $zip = "SmoothRoller_v${{ steps.version.outputs.version }}_win-x64.zip"
          Compress-Archive -Path "$dist/*" -DestinationPath $zip -Force
          "zip_path=$zip" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmoothRoller-v${{ steps.version.outputs.version }}-win-x64
          path: |
            ${{ steps.zip.outputs.zip_path }}
            dist/win-x64/**
            bin/Release/net6.0-windows/win-x64/publish/**